### ISSUE TITLE
Warum sind die Scripts doppelt im /eulenfunk

### ISSUE THREAD

**Issue by Adorfer** [eulenfunk/supernode#1]
Ich sehe die scripts zur Einrichtung für Supernode und Konzentrator sowohl in 
/eulenfunk/supernode + /eulenfunk/konzentrator also auch unter
/eulenfunk/scripts/supernode + /eulenfunk/scripts/konzentrator. 

Da in der Doku auf das "scripts"-verzeichnis verwiesen wird ist das hier vermutlich doppelt.
Kann es weg?

**Comment by ghost** [comment]
Die Scripte werden in eigene Repositories ausgelagert (siehe Issues in scripts. Daher: nein, kann hier nicht weg, sondern kommt aus scripts raus, sobald ich die Doku angepasst habe.
